  darknet.c
detector.obj : error LNK2019: __imp__pthread_join 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _load_network 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_base_args 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _free_data 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _load_data 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _read_data_cfg 외부 기호(참조 위치: _run_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _copy_cpu 외부 기호(참조 위치: _validate_detector_flip 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _save_image 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _demo 외부 기호(참조 위치: _run_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _option_find_str 외부 기호(참조 위치: _run_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _option_find_int 외부 기호(참조 위치: _run_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _save_weights 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _set_batch_network 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _load_image_color 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _make_image 외부 기호(참조 위치: _validate_detector_flip 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _resize_image 외부 기호(참조 위치: _validate_detector_recall 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _letterbox_image 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _resize_network 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_current_rate 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_current_batch 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _flip_image 외부 기호(참조 위치: _validate_detector_flip 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _box_iou 외부 기호(참조 위치: _validate_detector_recall 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _read_boxes 외부 기호(참조 위치: _validate_detector_recall 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _draw_detections 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _load_alphabet 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _network_predict 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_network_boxes 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _free_detections 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_labels 외부 기호(참조 위치: _run_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _do_nms_obj 외부 기호(참조 위치: _validate_detector_recall 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _do_nms_sort 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _free_image 외부 기호(참조 위치: _test_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _train_network 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _load_data_in_thread 외부 기호(참조 위치: _validate_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _get_paths 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
detector.obj : error LNK2019: _list_to_array 외부 기호(참조 위치: _train_detector 함수)에서 확인하지 못했습니다.
utils.obj : error LNK2019: _make_list 외부 기호(참조 위치: _parse_csv_line 함수)에서 확인하지 못했습니다.
utils.obj : error LNK2019: _list_insert 외부 기호(참조 위치: _parse_csv_line 함수)에서 확인하지 못했습니다.
..\..\pthreads-w32-2-9-1-release\Pre-built.2\lib\x64\pthreadVC2.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
D:\SSE\yolo_v3\Debug\yolo_v3.exe : fatal error LNK1120: 38개의 확인할 수 없는 외부 참조입니다.
